const config={businessName:'NOMBRE DEL NEGOCIO',whatsapp:'NUMERO_WHATSAPP_CON_CODIGO_PAIS',catalogUrl:'https://TU-USUARIO.github.io/TU-REPOSITORIO/',currency:'USD'};
const products=[
{name:'Producto de ejemplo 01',brand:'MARCA',price:0,category:'Categoría',image:'PRODUCTO_01.png',featured:true,description:'Reemplaza este producto de ejemplo por el producto del cliente.'},
{name:'Producto de ejemplo 02',brand:'MARCA',price:0,category:'Categoría',image:'PRODUCTO_02.png',description:'Reemplaza este producto de ejemplo por el producto del cliente.'}
];
let activeCategory='Todos',showFavorites=false;
let cart=readStorage('clientCatalogCart',{}),favorites=readStorage('clientCatalogFavorites',[]);
const $=s=>document.querySelector(s),money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:config.currency}).format(Number(v)||0);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function readStorage(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function wa(message){return `https://wa.me/${config.whatsapp}?text=${encodeURIComponent(message)}`}
function product(name){return products.find(p=>p.name===name)}
function cartLines(){return Object.entries(cart).map(([name,qty])=>({product:product(name),qty:Number(qty)})).filter(x=>x.product&&x.qty>0)}
function totals(){const lines=cartLines();return{lines,units:lines.reduce((s,x)=>s+x.qty,0),total:lines.reduce((s,x)=>s+x.product.price*x.qty,0)}}
function renderCategories(){const cats=['Todos',...new Set(products.map(p=>p.category))];$('#categories').innerHTML=cats.map(c=>`<button class="category ${c===activeCategory?'active':''}" type="button" data-category="${esc(c)}">${esc(c)}</button>`).join('')}
function renderBrands(){const brands=[...new Set(products.map(p=>p.brand))].sort();$('#brandFilter').innerHTML='<option value="all">Todas</option>'+brands.map(b=>`<option value="${esc(b)}">${esc(b)}</option>`).join('')}
function filteredProducts(){const q=$('#search').value.toLowerCase().trim(),brand=$('#brandFilter').value,sort=$('#sort').value;let list=products.filter(p=>(activeCategory==='Todos'||p.category===activeCategory)&&(brand==='all'||p.brand===brand)&&(!showFavorites||favorites.includes(p.name))&&(`${p.name} ${p.brand} ${p.category}`).toLowerCase().includes(q));if(sort==='price-asc')list.sort((a,b)=>a.price-b.price);if(sort==='price-desc')list.sort((a,b)=>b.price-a.price);if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));if(sort==='featured')list.sort((a,b)=>Number(b.featured)-Number(a.featured));return list}
function renderProducts(){const list=filteredProducts();$('#products').innerHTML=list.map(p=>{const fav=favorites.includes(p.name),qty=cart[p.name]||0;return `<article class="card"><div class="card-media"><img src="${esc(p.image)}" alt="${esc(p.name)} — ${esc(p.brand)}" loading="lazy" onerror="this.onerror=null;this.alt='Imagen no disponible';this.style.opacity='.35'"><button class="fav-button ${fav?'active':''}" type="button" data-fav="${esc(p.name)}" aria-label="${fav?'Quitar de favoritos':'Añadir a favoritos'}">${fav?'♥':'♡'}</button>${p.featured?'<span class="badge">⭐ Destacado</span>':''}</div><div class="card-content"><span class="category-label">${esc(p.brand)} · ${esc(p.category)}</span><h3>${esc(p.name)}</h3><div class="card-meta">🟢 Disponible</div><div class="price">${money(p.price)}</div><div class="product-actions"><button class="add-button" type="button" data-add="${esc(p.name)}">➕ Añadir</button><button class="details-button" type="button" data-details="${esc(p.name)}">Ver</button>${qty?`<span class="in-cart">✓ ${qty} en tu carrito</span>`:''}</div></div></article>`}).join('');$('#empty').hidden=list.length>0}
function renderFavorites(){const n=favorites.length;$('#favoriteCount').textContent=n;$('#favoritesFilter').classList.toggle('active',showFavorites);$('#favoritesFilter').firstChild.textContent=showFavorites?'♥ ':'♡ '}
function renderCart(){const{lines,units,total}=totals();$('#cartCount').textContent=units;$('#summaryUnits').textContent=units;$('#cartTotal').textContent=money(total);$('#cartEmpty').hidden=lines.length>0;$('#clearCart').disabled=!lines.length;$('#checkout').disabled=!lines.length;$('#cartItems').innerHTML=lines.map(({product:p,qty})=>`<div class="cart-item"><img src="${esc(p.image)}" alt="${esc(p.name)}"><div class="cart-item-info"><h3>${esc(p.name)}</h3><small>${esc(p.brand)}</small><strong>${money(p.price*qty)}</strong><div class="qty-controls"><button type="button" data-dec="${esc(p.name)}" aria-label="Disminuir">−</button><span>${qty}</span><button type="button" data-add="${esc(p.name)}" aria-label="Aumentar">+</button><button class="remove" type="button" data-remove="${esc(p.name)}">Eliminar</button></div></div></div>`).join('')}
function addToCart(name){cart[name]=(cart[name]||0)+1;save('clientCatalogCart',cart);renderProducts();renderCart();pulseCart()}
function decrease(name){if(!cart[name])return;if(cart[name]===1)delete cart[name];else cart[name]--;save('clientCatalogCart',cart);renderProducts();renderCart()}
function removeFromCart(name){delete cart[name];save('clientCatalogCart',cart);renderProducts();renderCart()}
function clearCart(){cart={};save('clientCatalogCart',cart);renderProducts();renderCart()}
function pulseCart(){const b=$('#openCart');b.animate([{transform:'scale(1)'},{transform:'scale(1.06)'},{transform:'scale(1)'}],{duration:280})}
function openCart(){closeModals();$('#cartPanel').classList.add('open');$('#cartPanel').setAttribute('aria-hidden','false');$('#cartOverlay').hidden=false;document.body.classList.add('cart-open')}
function closeCart(){if(!$('#cartPanel').classList.contains('open'))return;$('#cartPanel').classList.remove('open');$('#cartPanel').setAttribute('aria-hidden','true');$('#cartOverlay').hidden=true;document.body.classList.remove('cart-open')}
function showModal(id){closeCart();$('#modalBackdrop').hidden=false;$(id).hidden=false;document.body.classList.add('modal-open')}
function closeModals(){document.querySelectorAll('.modal').forEach(m=>m.hidden=true);$('#modalBackdrop').hidden=true;document.body.classList.remove('modal-open')}
function showProduct(name){const p=product(name);if(!p)return;$('#productModalBody').innerHTML=`<div class="product-detail"><img src="${esc(p.image)}" alt="${esc(p.name)}"><div><span class="category-label">${esc(p.brand)} · ${esc(p.category)}</span><h2 id="productModalTitle">${esc(p.name)}</h2><div class="detail-price">${money(p.price)}</div><p class="detail-note">${esc(p.description)}</p><p class="detail-note">🟢 Disponible · Pedido confirmado por WhatsApp.</p><button class="checkout" type="button" data-add="${esc(p.name)}">➕ Añadir al carrito</button></div></div>`;showModal('#productModal')}
function openCheckout(){const{lines,total,units}=totals();if(!lines.length)return;$('#orderPreview').innerHTML=lines.map(x=>`<div class="order-line"><span>${x.qty} × ${esc(x.product.name)}</span><strong>${money(x.product.price*x.qty)}</strong></div>`).join('')+`<div class="order-total"><span>${units} productos</span><span>${money(total)}</span></div>`;showModal('#checkoutModal')}
function submitCheckout(e){e.preventDefault();const{lines,total,units}=totals();if(!lines.length)return;const f=new FormData(e.target);const name=f.get('name').trim(),phone=f.get('phone').trim(),city=f.get('city').trim(),delivery=f.get('delivery'),payment=f.get('payment'),address=f.get('address').trim(),note=f.get('note').trim();const detail=lines.map(x=>`${x.qty} x ${x.product.name} — ${money(x.product.price*x.qty)}`).join('\n');let text=`Hola, quiero realizar este pedido en ${config.businessName}.\n\nPEDIDO:\n${detail}\n\nTotal de productos: ${units}\nTOTAL: ${money(total)}\n\nDATOS DEL CLIENTE:\nNombre: ${name}\nTeléfono: ${phone||'No indicado'}\nCiudad/zona: ${city}\nEntrega: ${delivery}\nMétodo de pago: ${payment}`;if(address)text+=`\nDirección/referencia: ${address}`;if(note)text+=`\nNota: ${note}`;text+='\n\n¿Me confirman disponibilidad y cómo continuar con el pedido?';window.open(wa(text),'_blank','noopener');closeModals()}
function shareCatalog(){if(navigator.share)navigator.share({title:config.businessName,text:`Mira el catálogo de ${config.businessName}`,url:config.catalogUrl}).catch(()=>{});else{navigator.clipboard?.writeText(config.catalogUrl);alert('Enlace del catálogo copiado.')} }
function showInfo(type){if(type==='about'){$('#infoTitle').textContent='Cómo comprar';$('#infoBody').innerHTML='<ol><li>Busca o filtra tus productos favoritos.</li><li>Pulsa <b>Añadir</b> y ajusta las cantidades en el carrito.</li><li>Revisa el total y pulsa <b>Continuar con el pedido</b>.</li><li>Completa tus datos y envía el pedido por WhatsApp.</li><li>El negocio confirmará disponibilidad, entrega y pago.</li></ol><p class="detail-note">💗 Los productos y precios se muestran en el catálogo. Los tonos o variantes, cuando existan, se confirman por WhatsApp.</p>'}else{$('#infoTitle').textContent='Privacidad';$('#infoBody').innerHTML='<p class="detail-note">Este catálogo guarda únicamente en tu navegador los favoritos y el carrito para que no se pierdan al recargar la página. Al enviar un pedido, los datos que escribas se comparten directamente con el negocio mediante WhatsApp. El catálogo no procesa pagos dentro de la página.</p>'}showModal('#infoModal')}
function initQR(){if(typeof QRCode!=='undefined')new QRCode($('#qrcode'),{text:config.catalogUrl,width:140,height:140,correctLevel:QRCode.CorrectLevel.H})}
function registerSW(){if('serviceWorker' in navigator&&location.protocol==='https:')navigator.serviceWorker.register('sw.js').catch(()=>{})}
function init(){
  $('#mainWhatsapp').href=wa(`Hola, quiero información sobre los productos de ${config.businessName}.`);$('#footerWhatsapp').href=wa(`Hola, quiero información sobre el catálogo de ${config.businessName}.`);
  renderCategories();renderBrands();renderProducts();renderFavorites();renderCart();initQR();registerSW();
  $('#search').addEventListener('input',renderProducts);$('#sort').addEventListener('change',renderProducts);$('#brandFilter').addEventListener('change',renderProducts);
  $('#openCart').addEventListener('click',openCart);$('#closeCart').addEventListener('click',closeCart);$('#cartOverlay').addEventListener('click',closeCart);$('#checkout').addEventListener('click',openCheckout);$('#clearCart').addEventListener('click',clearCart);$('#favoritesFilter').addEventListener('click',()=>{showFavorites=!showFavorites;renderFavorites();renderProducts()});$('#clearFilters').addEventListener('click',()=>{$('#search').value='';$('#brandFilter').value='all';$('#sort').value='featured';activeCategory='Todos';showFavorites=false;renderCategories();renderFavorites();renderProducts()});$('#shareCatalog').addEventListener('click',shareCatalog);$('#aboutBtn').addEventListener('click',()=>showInfo('about'));$('#privacyBtn').addEventListener('click',()=>showInfo('privacy'));$('#checkoutForm').addEventListener('submit',submitCheckout);
  $('#categories').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(b){activeCategory=b.dataset.category;renderCategories();renderProducts()}});
  $('#products').addEventListener('click',e=>{const fav=e.target.closest('[data-fav]'),add=e.target.closest('[data-add]'),details=e.target.closest('[data-details]');if(fav){const n=fav.dataset.fav;favorites.includes(n)?favorites=favorites.filter(x=>x!==n):favorites.push(n);save('clientCatalogFavorites',favorites);renderFavorites();renderProducts()}else if(add)addToCart(add.dataset.add);else if(details)showProduct(details.dataset.details)});
  $('#cartItems').addEventListener('click',e=>{const add=e.target.closest('[data-add]'),dec=e.target.closest('[data-dec]'),rem=e.target.closest('[data-remove]');if(add)addToCart(add.dataset.add);if(dec)decrease(dec.dataset.dec);if(rem)removeFromCart(rem.dataset.remove)});
  document.addEventListener('click',e=>{if(e.target.matches('[data-close-modal]'))closeModals()});$('#modalBackdrop').addEventListener('click',closeModals);document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCart();closeModals()}});
}
init();