const KEY='catalogoeditAdminData';
const DEFAULT={config:{businessName:'Belleza Studio',whatsapp:'',currency:'USD',tagline:'Belleza · estilo · cuidado',welcomeTitle:'Todo lo que buscas, en un solo lugar',welcomeText:'Encuentra tus favoritos, guárdalos, agrégalos al carrito y envía tu pedido por WhatsApp.',primaryColor:'#9b6879',backgroundColor:'#f7f2f4',logoUrl:'../logo.svg',orderMessage:''},products:[{name:'Serum Renovador',brand:'Belleza Studio',price:24.9,category:'Cuidado facial',image:'../demo/producto-01.svg',featured:true,description:'Serum ligero para una rutina de cuidado facial elegante y sencilla.'},{name:'Crema Hidratante',brand:'Belleza Studio',price:19.9,category:'Cuidado facial',image:'../demo/producto-02.svg',featured:true,description:'Hidratación diaria con textura suave y acabado confortable.'},{name:'Shampoo Nutritivo',brand:'Belleza Studio',price:16.5,category:'Cabello',image:'../demo/producto-03.svg',featured:false,description:'Limpieza suave para una rutina capilar de uso diario.'}]};
let data=load();
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.config&&Array.isArray(x.products))return x}catch{}return structuredClone(DEFAULT)}
function persist(){localStorage.setItem(KEY,JSON.stringify(data));toast('Cambios guardados en este dispositivo')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
function renderList(){const q=$('#productSearch').value.toLowerCase().trim(),cat=$('#categoryFilter').value;const list=data.products.map((p,i)=>({p,i})).filter(({p})=>(cat==='all'||p.category===cat)&&(`${p.name} ${p.brand} ${p.category}`).toLowerCase().includes(q));$('#productList').innerHTML=list.length?list.map(({p,i})=>`<div class="product-row"><img src="${esc(p.image)}" alt=""><div><h3>${esc(p.name)} ${p.featured?'⭐':''}</h3><p>${esc(p.brand||'')} · ${esc(p.category||'')}</p></div><span class="price">${Number(p.price||0).toFixed(2)}</span><button class="edit-btn" data-edit="${i}">Editar</button></div>`).join(''):'<div class="empty-row">No hay productos que coincidan.</div>';renderCategories()}
function renderCategories(){const cats=[...new Set(data.products.map(p=>p.category).filter(Boolean))].sort(),old=$('#categoryFilter').value;$('#categoryFilter').innerHTML='<option value="all">Todas las categorías</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');if(cats.includes(old))$('#categoryFilter').value=old}
function fillBrand(){const c=data.config;$('#businessName').value=c.businessName||'';$('#tagline').value=c.tagline||'';$('#welcomeTitle').value=c.welcomeTitle||'';$('#welcomeText').value=c.welcomeText||'';$('#primaryColor').value=c.primaryColor||'#9b6879';$('#backgroundColor').value=c.backgroundColor||'#f7f2f4';$('#logoUrl').value=c.logoUrl||'../logo.svg';$('#whatsapp').value=c.whatsapp||'';$('#currency').value=c.currency||'USD';$('#orderMessage').value=c.orderMessage||''}
function readBrand(){const c=data.config;c.businessName=$('#businessName').value.trim()||'Catálogo Online';c.tagline=$('#tagline').value.trim();c.welcomeTitle=$('#welcomeTitle').value.trim();c.welcomeText=$('#welcomeText').value.trim();c.primaryColor=$('#primaryColor').value;c.backgroundColor=$('#backgroundColor').value;c.logoUrl=$('#logoUrl').value.trim()||'../logo.svg';c.whatsapp=$('#whatsapp').value.trim();c.currency=$('#currency').value;c.orderMessage=$('#orderMessage').value.trim()}
function openEditor(index=-1){$('#editorModal').classList.remove('hidden');$('#productIndex').value=index;$('#modalTitle').textContent=index<0?'Nuevo producto':'Editar producto';$('#deleteProduct').style.display=index<0?'none':'inline-block';const p=index<0?{name:'',brand:data.config.businessName,price:0,category:'',image:'../demo/producto-01.svg',featured:false,description:''}:data.products[index];$('#pName').value=p.name;$('#pBrand').value=p.brand||'';$('#pPrice').value=p.price??0;$('#pCategory').value=p.category||'';$('#pDescription').value=p.description||'';$('#pImage').value=p.image||'';$('#pFeatured').checked=!!p.featured}
function closeEditor(){$('#editorModal').classList.add('hidden')}
function saveProduct(e){e.preventDefault();const i=Number($('#productIndex').value),p={name:$('#pName').value.trim(),brand:$('#pBrand').value.trim(),price:Number($('#pPrice').value)||0,category:$('#pCategory').value.trim(),description:$('#pDescription').value.trim(),image:$('#pImage').value.trim()||'../demo/producto-01.svg',featured:$('#pFeatured').checked};if(i<0)data.products.push(p);else data.products[i]=p;closeEditor();renderList();persist()}
function deleteProduct(){const i=Number($('#productIndex').value);if(!Number.isInteger(i)||i<0)return;if(confirm('¿Eliminar este producto?')){data.products.splice(i,1);closeEditor();renderList();persist()}}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportJson(){download('catalogoedit-copia.json',JSON.stringify(data,null,2),'application/json')}
function csv(){const head=['name','brand','price','category','image','featured','description'];const rows=data.products.map(p=>head.map(k=>`"${String(p[k]??'').replace(/"/g,'""')}"`).join(','));return head.join(',')+'\n'+rows.join('\n')}
function exportCsv(){download('catalogoedit-productos.csv',csv(),'text/csv;charset=utf-8')}
function importJson(e){const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.config||!Array.isArray(x.products))throw Error();data=x;fillBrand();renderList();persist();toast('Catálogo restaurado')}catch{alert('El archivo no tiene un formato válido de CatálogoEdit.')}};r.readAsText(file)}
function reset(){if(confirm('¿Restablecer la demo? Esto reemplazará los cambios locales de este navegador.')){data=structuredClone(DEFAULT);fillBrand();renderList();persist()}}
function tabs(){document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));b.classList.add('active');$('#tab-'+b.dataset.tab).classList.remove('hidden')}))}
function init(){fillBrand();renderList();tabs();$('#saveBtn').addEventListener('click',()=>{readBrand();persist()});$('#newProduct').addEventListener('click',()=>openEditor());$('#productList').addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(b)openEditor(Number(b.dataset.edit))});$('#productSearch').addEventListener('input',renderList);$('#categoryFilter').addEventListener('change',renderList);$('#bulkExport').addEventListener('click',exportCsv);$('#exportJson').addEventListener('click',exportJson);$('#exportCsv').addEventListener('click',exportCsv);$('#importJson').addEventListener('change',importJson);$('#resetDemo').addEventListener('click',reset);$('#closeModal').addEventListener('click',closeEditor);$('#productForm').addEventListener('submit',saveProduct);$('#deleteProduct').addEventListener('click',deleteProduct);}
init();
