const KEY='catalogoeditAdminData';
const DEFAULT={config:{businessName:'Belleza Studio',whatsapp:'',currency:'USD',tagline:'Belleza · estilo · cuidado',welcomeTitle:'Todo lo que buscas, en un solo lugar',welcomeText:'Encuentra tus favoritos, guárdalos, agrégalos al carrito y envía tu pedido por WhatsApp.',primaryColor:'#9b6879',backgroundColor:'#f7f2f4',cardColor:'#ffffff',logoUrl:'logo.svg',orderMessage:'',cardStyle:'soft',buttonStyle:'rounded',imageStyle:'portrait',showTrust:true,showQr:true,showFavorites:true,showFooter:true,announcement:'',announcementLabel:'NOVEDAD'},products:[{name:'Serum Renovador',brand:'Belleza Studio',price:24.9,category:'Cuidado facial',image:'demo/producto-01.svg',featured:true,description:'Serum ligero para una rutina de cuidado facial elegante y sencilla.'},{name:'Crema Hidratante',brand:'Belleza Studio',price:19.9,category:'Cuidado facial',image:'demo/producto-02.svg',featured:true,description:'Hidratación diaria con textura suave y acabado confortable.'},{name:'Shampoo Nutritivo',brand:'Belleza Studio',price:16.5,category:'Cabello',image:'demo/producto-03.svg',featured:false,description:'Limpieza suave para una rutina capilar de uso diario.'}]};
let data=load();
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.config&&Array.isArray(x.products))return {...structuredClone(DEFAULT),...x,config:{...DEFAULT.config,...x.config}}}catch{}return structuredClone(DEFAULT)}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(data));toast('Cambios guardados en este dispositivo')}catch{alert('No hay espacio suficiente para guardar. Reduce el tamaño de una foto o exporta una copia.')}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
function renderList(){const q=$('#productSearch').value.toLowerCase().trim(),cat=$('#categoryFilter').value;const list=data.products.map((p,i)=>({p,i})).filter(({p})=>(cat==='all'||p.category===cat)&&(`${p.name} ${p.brand} ${p.category}`).toLowerCase().includes(q));$('#productList').innerHTML=list.length?list.map(({p,i})=>`<div class="product-row"><img src="${esc(String(p.image||'').replace(/^\.\.\//,''))}" alt=""><div><h3>${esc(p.name)} ${p.featured?'⭐':''}</h3><p>${esc(p.brand||'')} · ${esc(p.category||'')}</p></div><span class="price">${Number(p.price||0).toFixed(2)}</span><button class="edit-btn" data-edit="${i}">Editar</button></div>`).join(''):'<div class="empty-row">No hay productos que coincidan.</div>';renderCategories()}
function renderCategories(){const cats=[...new Set(data.products.map(p=>p.category).filter(Boolean))].sort(),old=$('#categoryFilter').value;$('#categoryFilter').innerHTML='<option value="all">Todas las categorías</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');if(cats.includes(old))$('#categoryFilter').value=old}
function fillBrand(){const c=data.config;$('#businessName').value=c.businessName||'';$('#tagline').value=c.tagline||'';$('#welcomeTitle').value=c.welcomeTitle||'';$('#welcomeText').value=c.welcomeText||'';$('#primaryColor').value=c.primaryColor||'#9b6879';$('#backgroundColor').value=c.backgroundColor||'#f7f2f4';$('#cardColor').value=c.cardColor||'#ffffff';$('#logoUrl').value=c.logoUrl||'logo.svg';$('#whatsapp').value=c.whatsapp||'';$('#currency').value=c.currency||'USD';$('#orderMessage').value=c.orderMessage||'';$('#cardStyle').value=c.cardStyle||'soft';$('#buttonStyle').value=c.buttonStyle||'rounded';$('#imageStyle').value=c.imageStyle||'portrait';$('#showTrust').checked=c.showTrust!==false;$('#showQr').checked=c.showQr!==false;$('#showFavorites').checked=c.showFavorites!==false;$('#showFooter').checked=c.showFooter!==false;$('#announcement').value=c.announcement||'';$('#announcementLabel').value=c.announcementLabel||'NOVEDAD';updatePreview()}
function readBrand(){const c=data.config;c.businessName=$('#businessName').value.trim()||'Catálogo Online';c.tagline=$('#tagline').value.trim();c.welcomeTitle=$('#welcomeTitle').value.trim();c.welcomeText=$('#welcomeText').value.trim();c.primaryColor=$('#primaryColor').value;c.backgroundColor=$('#backgroundColor').value;c.cardColor=$('#cardColor').value;c.logoUrl=$('#logoUrl').value.trim()||'logo.svg';c.whatsapp=$('#whatsapp').value.trim();c.currency=$('#currency').value;c.orderMessage=$('#orderMessage').value.trim();c.cardStyle=$('#cardStyle').value;c.buttonStyle=$('#buttonStyle').value;c.imageStyle=$('#imageStyle').value;c.showTrust=$('#showTrust').checked;c.showQr=$('#showQr').checked;c.showFavorites=$('#showFavorites').checked;c.showFooter=$('#showFooter').checked;c.announcement=$('#announcement').value.trim();c.announcementLabel=$('#announcementLabel').value.trim()||'NOVEDAD'}
function updatePreview(){const c=data.config,el=$('#stylePreviewCard');if(!el)return;el.style.background=c.cardColor||'#fff';el.style.borderColor=c.primaryColor||'#ddd';el.style.borderRadius=c.cardStyle==='luxury'?'4px':c.cardStyle==='clean'?'10px':'18px';el.querySelector('button').style.background=c.primaryColor||'#17151a';el.querySelector('button').style.borderRadius=c.buttonStyle==='square'?'5px':c.buttonStyle==='soft'?'10px':'999px'}
function openEditor(index=-1){$('#editorModal').classList.remove('hidden');$('#productIndex').value=index;$('#modalTitle').textContent=index<0?'Nuevo producto':'Editar producto';$('#deleteProduct').style.display=index<0?'none':'inline-block';const p=index<0?{name:'',brand:data.config.businessName,price:0,category:'',image:'',featured:false,description:''}:data.products[index];$('#pName').value=p.name;$('#pBrand').value=p.brand||'';$('#pPrice').value=p.price??0;$('#pCategory').value=p.category||'';$('#pDescription').value=p.description||'';$('#pImage').value=String(p.image||'').replace(/^\.\.\//,'');$('#pFeatured').checked=!!p.featured;$('#pImageFile').value='';setImagePreview(p.image||'')}
function closeEditor(){$('#editorModal').classList.add('hidden')}
function setImagePreview(src){const img=$('#imagePreview');if(src){img.src=src;img.classList.add('visible')}else{img.removeAttribute('src');img.classList.remove('visible')}}
function imageToDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
async function handleImage(e){const file=e.target.files[0];if(!file)return;if(!file.type.startsWith('image/'))return alert('Selecciona una imagen.');if(file.size>4*1024*1024)return alert('Para este MVP usa una foto de hasta 4 MB.');try{const url=await imageToDataUrl(file);$('#pImage').value=url;setImagePreview(url)}catch{alert('No se pudo leer la imagen.')}}
const descriptionPools={beauty:['realza tu rutina con una propuesta práctica y agradable de usar','combina una presentación cuidada con beneficios pensados para el cuidado diario','es una alternativa cómoda para quienes buscan incorporar este tipo de producto a su rutina'],hair:['acompaña el cuidado diario del cabello con una experiencia suave y práctica','está pensado para complementar una rutina capilar sencilla y constante','ofrece una opción cómoda para mantener una rutina de cabello bien cuidada'],tech:['ofrece una solución práctica para aprovechar mejor tus dispositivos en el día a día','combina funcionalidad y comodidad para acompañar tus equipos y accesorios','es una alternativa útil para quienes buscan practicidad y buen desempeño en su rutina tecnológica'],hardware:['está pensado para resolver tareas cotidianas de forma práctica y eficiente','ofrece una solución funcional para trabajos, reparaciones y proyectos del hogar','combina utilidad y facilidad de uso para acompañar diferentes proyectos'],fashion:['aporta personalidad y versatilidad para completar diferentes looks','combina estilo y practicidad para integrarse fácilmente a tu forma de vestir','es una pieza pensada para quienes buscan renovar su estilo con facilidad'],home:['ayuda a crear un espacio más práctico y agradable en el día a día','combina funcionalidad y comodidad para diferentes momentos del hogar','es una opción versátil para complementar tus espacios'],food:['es una opción pensada para disfrutar y compartir en diferentes ocasiones','combina una propuesta atractiva con la practicidad que buscas para disfrutarla','está pensado para acompañar tus momentos de consumo de forma sencilla']};
function productType(text){if(/serum|suero|crema|hidrat|facial|skincare|maquill|labial|perfume|cosmet/.test(text))return'beauty';if(/shampoo|cabello|pelo|mascarilla|acondicionador/.test(text))return'hair';if(/celular|phone|cargador|cable|audif|audífono|gadg|tecnolog|usb|bluetooth/.test(text))return'tech';if(/ferreter|herramienta|taladro|tornillo|constru|martillo/.test(text))return'hardware';if(/ropa|camisa|vestido|pantalon|zapato|moda|falda/.test(text))return'fashion';if(/cocina|hogar|casa|organizador|decor/.test(text))return'home';if(/café|cafe|comida|snack|dulce|galleta|bebida/.test(text))return'food';return'general'}
function autoDescription(){const name=$('#pName').value.trim()||'Este producto',brand=$('#pBrand').value.trim(),cat=$('#pCategory').value.trim()||'uso diario',text=(name+' '+cat).toLowerCase(),type=productType(text),pool=descriptionPools[type]||['una propuesta práctica y versátil para acompañar tus necesidades del día a día','una alternativa pensada para combinar utilidad, comodidad y una presentación cuidada','una opción funcional para quienes buscan calidad y facilidad de uso'];let last=$('#pDescription').value.trim();let choices=pool.filter(x=>!last.includes(x));if(!choices.length)choices=pool;const phrase=choices[Math.floor(Math.random()*choices.length)];const endings=['Una elección pensada para comprar con confianza y disfrutar de una experiencia sencilla.','Ideal para complementar tu día a día con una solución práctica y bien presentada.','Descubre sus características y elige la opción que mejor se adapte a tus necesidades.'];let ending=endings[Math.floor(Math.random()*endings.length)];$('#pDescription').value=`${name}${brand?` de ${brand}`:''}: ${phrase}. ${ending}`;toast('Nueva descripción generada')}
function saveProduct(e){e.preventDefault();const i=Number($('#productIndex').value),p={name:$('#pName').value.trim(),brand:$('#pBrand').value.trim(),price:Number($('#pPrice').value)||0,category:$('#pCategory').value.trim(),description:$('#pDescription').value.trim(),image:$('#pImage').value.trim().replace(/^\.\.\//,'')||'demo/producto-01.svg',featured:$('#pFeatured').checked};if(!p.name||!p.category)return alert('Completa nombre y categoría.');if(i<0)data.products.push(p);else data.products[i]=p;closeEditor();renderList();persist()}
function deleteProduct(){const i=Number($('#productIndex').value);if(!Number.isInteger(i)||i<0)return;if(confirm('¿Eliminar este producto?')){data.products.splice(i,1);closeEditor();renderList();persist()}}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportJson(){download('catalogoedit-copia.json',JSON.stringify(data,null,2),'application/json')}
function csv(){const head=['name','brand','price','category','image','featured','description'];const rows=data.products.map(p=>head.map(k=>`"${String(p[k]??'').replace(/"/g,'""')}"`).join(','));return head.join(',')+'\n'+rows.join('\n')}
function exportCsv(){download('catalogoedit-productos.csv',csv(),'text/csv;charset=utf-8')}
function importJson(e){const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.config||!Array.isArray(x.products))throw Error();data={...structuredClone(DEFAULT),...x,config:{...DEFAULT.config,...x.config}};data.products=data.products.map(p=>({...p,image:String(p.image||'').replace(/^\.\.\//,'')}));fillBrand();renderList();persist();toast('Catálogo restaurado')}catch{alert('El archivo no tiene un formato válido de CatálogoEdit.')}};r.readAsText(file)}
function reset(){if(confirm('¿Restablecer la demo? Esto reemplazará los cambios locales de este navegador.')){data=structuredClone(DEFAULT);fillBrand();renderList();persist()}}
function tabs(){document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));b.classList.add('active');$('#tab-'+b.dataset.tab).classList.remove('hidden')}))}
function init(){fillBrand();renderList();tabs();$('#saveBtn').addEventListener('click',()=>{readBrand();persist();updatePreview()});$('#newProduct').addEventListener('click',()=>openEditor());$('#productList').addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(b)openEditor(Number(b.dataset.edit))});$('#productSearch').addEventListener('input',renderList);$('#categoryFilter').addEventListener('change',renderList);$('#bulkExport').addEventListener('click',exportCsv);$('#exportJson').addEventListener('click',exportJson);$('#exportCsv').addEventListener('click',exportCsv);$('#importJson').addEventListener('change',importJson);$('#resetDemo').addEventListener('click',reset);$('#closeModal').addEventListener('click',closeEditor);$('#productForm').addEventListener('submit',saveProduct);$('#deleteProduct').addEventListener('click',deleteProduct);$('#pImageFile').addEventListener('change',handleImage);$('#pImage').addEventListener('input',e=>setImagePreview(e.target.value.trim()));$('#generateDescription').addEventListener('click',autoDescription);['#cardStyle','#buttonStyle','#primaryColor','#cardColor'].forEach(sel=>$(sel)?.addEventListener('input',()=>{readBrand();updatePreview()}))}
init();