const KEY='catalogoeditAdminData';
const BACKGROUNDS={
  solid:{label:'Color sólido',css:(c)=>c.backgroundColor||'#f7f2f4'},
  blush:{label:'Blush degradado',css:()=> 'linear-gradient(135deg,#fff8f8 0%,#f3dce4 48%,#ead0da 100%)'},
  champagne:{label:'Champagne suave',css:()=> 'radial-gradient(circle at 15% 20%,rgba(255,255,255,.95),transparent 35%),linear-gradient(135deg,#f7efe6,#ead9c8 55%,#f4e8dc)'},
  botanical:{label:'Botánico',css:()=> 'radial-gradient(circle at 85% 15%,rgba(139,171,143,.25),transparent 28%),radial-gradient(circle at 15% 80%,rgba(114,150,120,.18),transparent 30%),linear-gradient(135deg,#f8f7f0,#e6eee5)'},
  ocean:{label:'Azul editorial',css:()=> 'radial-gradient(circle at 80% 10%,rgba(255,255,255,.28),transparent 28%),linear-gradient(135deg,#eef5f7,#d7e7ec 50%,#c6dce3)'},
  night:{label:'Negro premium',css:()=> 'radial-gradient(circle at 80% 15%,rgba(190,160,120,.18),transparent 30%),linear-gradient(135deg,#17151a,#29232b 55%,#3b3038)'},
  paper:{label:'Papel editorial',css:()=> 'repeating-linear-gradient(0deg,rgba(90,70,50,.025) 0,rgba(90,70,50,.025) 1px,transparent 1px,transparent 5px),linear-gradient(135deg,#faf7f1,#f1ece4)'},
  mesh:{label:'Malla moderna',css:()=> 'radial-gradient(circle at 20% 20%,rgba(190,126,153,.22),transparent 24%),radial-gradient(circle at 80% 70%,rgba(120,150,190,.16),transparent 26%),linear-gradient(135deg,#fbf7f8,#f1edf5)'}
};
function getData(){try{return JSON.parse(localStorage.getItem(KEY))||null}catch{return null}}
function saveData(d){localStorage.setItem(KEY,JSON.stringify(d))}
function applyBackground(d){const c=d.config;let bg=c.backgroundType||'solid';let value=BACKGROUNDS[bg]?BACKGROUNDS[bg].css(c):c.backgroundColor||'#f7f2f4';if(bg==='custom'&&c.backgroundImage)value=`url("${c.backgroundImage}")`;const root=document.documentElement;root.style.setProperty('--studio-background',value);const target=document.body;target.style.background=value;target.style.backgroundAttachment='fixed';target.style.backgroundSize=bg==='custom'?'cover':'auto';target.dataset.backgroundType=bg}
function refreshPreview(){const d=getData();if(!d)return;applyBackground(d);const p=document.querySelector('#backgroundPreview');if(p){const c=d.config;p.style.background= c.backgroundType==='custom'&&c.backgroundImage?`url("${c.backgroundImage}")`:BACKGROUNDS[c.backgroundType||'solid']?.css(c)||c.backgroundColor||'#f7f2f4'}}
function initBackgroundStudio(){const d=getData();if(!d)return;d.config.backgroundType=d.config.backgroundType||'solid';const select=document.querySelector('#backgroundType');if(select)select.value=d.config.backgroundType;const file=document.querySelector('#backgroundFile');const save=()=>{d.config.backgroundType=select?.value||'solid';saveData(d);refreshPreview();if(typeof toast==='function')toast('Fondo actualizado')};select?.addEventListener('change',save);file?.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return alert('Selecciona una imagen.');if(f.size>5*1024*1024)return alert('La imagen de fondo debe pesar máximo 5 MB.');const r=new FileReader();r.onload=()=>{d.config.backgroundType='custom';d.config.backgroundImage=r.result;saveData(d);if(select)select.value='custom';refreshPreview();if(typeof toast==='function')toast('Fondo personalizado guardado')};r.readAsDataURL(f)});document.querySelector('#backgroundClear')?.addEventListener('click',()=>{d.config.backgroundType='solid';d.config.backgroundImage='';saveData(d);if(select)select.value='solid';refreshPreview();if(typeof toast==='function')toast('Fondo restablecido')});refreshPreview()}
window.addEventListener('load',initBackgroundStudio);